[[redirects]]
  from = "/pages/experiences/"
  to = "/pages/experiences/index.html"
  status = 200

[[redirects]]
  from = "/pages/gallery/"
  to = "/pages/gallery/index.html"
  status = 200

[[redirects]]
  from = "/pages/about-us/"
  to = "/pages/about-us/index.html"
  status = 200

[[redirects]]
  from = "/pages/booking/"
  to = "/pages/booking/index.html"
  status = 200